### ISSUE TITLE
Syntax warning when using Ipython

### ISSUE THREAD

**Issue by asm582** [IBMSpectrumComputing/lsf-faas#3]
Hello, I have an anaconda env and when I start ipython shell I get below syntax warnings:

(base) [asmalvan@ccc2-login-01 lsf-faas]$ ipython
Python 3.8.3 (default, Jul  2 2020, 16:21:59) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.
/home/asmalvan/.ipython/profile_default/startup/lsf.py:99: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if word is not 'import' and word is not 'from' and (missed_module == word or missed_module in word):
/home/asmalvan/.ipython/profile_default/startup/lsf.py:99: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if word is not 'import' and word is not 'from' and (missed_module == word or missed_module in word):

**Comment by xawyong** [comment]
the warning message is from  python3.8+, and I had fixed it #5 .  please @xunpan reviewing
